# Generated by Django 5.0.6 on 2024-09-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="custom_user",
            name="Age",
        ),
        migrations.RemoveField(
            model_name="custom_user",
            name="Contact_No",
        ),
        migrations.AlterField(
            model_name="custom_user",
            name="user_type",
            field=models.CharField(
                choices=[("admin", "Admin"), ("viewer", "Viewer")],
                max_length=100,
                null=True,
            ),
        ),
    ]
