# Generated by Django 5.0.6 on 2024-09-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0002_remove_custom_user_age_remove_custom_user_contact_no_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("file", models.FileField(upload_to="resumes/")),
            ],
        ),
    ]
