# Generated by Django 5.0.6 on 2024-09-07 05:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0003_resume"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Resume",
            new_name="ResumeModel",
        ),
    ]
