# Generated by Django 5.0.6 on 2024-09-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0004_rename_resume_resumemodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumemodel",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resumemodel",
            name="education",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resumemodel",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="resumemodel",
            name="experience",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resumemodel",
            name="github_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resumemodel",
            name="linkedin_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resumemodel",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="resumemodel",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="resumemodel",
            name="portfolio_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resumemodel",
            name="skills",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="resumemodel",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="resumemodel",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="resumes/"),
        ),
        migrations.AlterField(
            model_name="resumemodel",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
