# Generated by Django 5.0.6 on 2024-09-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0005_resumemodel_address_resumemodel_education_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumemodel",
            name="profile_pic",
            field=models.ImageField(null=True, upload_to="Media/Pro_pic"),
        ),
    ]
